name: WakaTime Readme Stats
on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar waka-readme-stats
        run: |
          git clone https://github.com/anmol098/waka-readme-stats.git
          cd waka-readme-stats

      - name: Instalar dependencias
        run: |
          cd waka-readme-stats
          pip install -r requirements.txt

      - name: Ejecutar script para generar waka.svg
        run: |
          cd waka-readme-stats
          python main.py

      - name: Commit cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add waka-readme-stats/waka.svg README.md
          git commit -m 'Actualizar README con estadísticas de WakaTime'
          git push
